# Generated by Django 3.2.4 on 2021-06-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='profile',
        ),
    ]
