# Generated by Django 3.2.4 on 2021-06-07 14:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0002_auto_20210604_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='occupants_count',
        ),
        migrations.AddField(
            model_name='business',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='business image'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='hood image'),
        ),
    ]
